name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Check out the repository
      uses: actions/checkout@v3

    # Шаг 2: Устанавливаем .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    # Шаг 3: Восстанавливаем зависимости
    - name: Restore dependencies
      run: dotnet restore

    # Шаг 4: Собираем проект
    - name: Build the project
      run: dotnet build --configuration Release

    # Шаг 5: Запускаем unit-тесты (если они есть)
    - name: Run tests
      run: dotnet test --configuration Release

    # Шаг 6: Публикуем проект
    - name: Publish the project
      run: dotnet publish --configuration Release --output ./out

    # Шаг 7: Собираем Docker-образ
    - name: Build Docker image
      run: |
        docker build -t laba2 -f laba2/Dockerfile laba2
